#!/usr/bin/env bash
# Display the contents of the current directory in a list format
# Only display the part of the name after the first dash

for file in *; do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
        filename=${file#*-}
        echo "$filename"
    fi
done
